
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 255754134813.dkr.ecr.us-west-2.amazonaws.com/shopping-site-backend:18d0d24b4103aa4b56a171f41a411f860bb29816
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP