apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobiles-deployment
  labels:
    app: mobiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobiles
  template:
    metadata:
      labels:
        app: mobiles
    spec:
      containers:
      - name: mobiles
        image: 255754134813.dkr.ecr.us-west-2.amazonaws.com/shopping-site-mobiles:18d0d24b4103aa4b56a171f41a411f860bb29816
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mobiles-service
  labels:
    app: mobiles
spec:
  type: ClusterIP
  selector:
    app: mobiles
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
