apiVersion: apps/v1
kind: Deployment
metadata:
  name: beauty-deployment
  labels:
    app: beauty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beauty
  template:
    metadata:
      labels:
        app: beauty
    spec:
      containers:
      - name: beauty
        image: 295129427067.dkr.ecr.us-east-1.amazonaws.com/shopping-site-beauty:7e15eee7b92e9264da188e44ef2f7389bcdfbdbe
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: beauty-service
  labels:
    app: beauty
spec:
  type: ClusterIP
  selector:
    app: beauty
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
