apiVersion: apps/v1
kind: Deployment
metadata:
  name: toys-deployment
  labels:
    app: toys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toys
  template:
    metadata:
      labels:
        app: toys
    spec:
      containers:
      - name: toys
        image: 767397972310.dkr.ecr.us-east-1.amazonaws.com/shopping-site-toys:e89b1b8fdc905205124b1524a05e4c8ca92f1bf6
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: toys-service
  labels:
    app: toys
spec:
  type: ClusterIP
  selector:
    app: toys
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
